In [1]:
import pandas as pd
# train = pd.read_csv('data/train.csv')
train = pd.read_csv('train_preprocessed.csv')

In [2]:
from pycaret.datasets import get_data 
from pycaret.classification import *
from pycaret.utils import check_metric

In [3]:
# setup으로 init
clf = setup(data=train, target='ProdTaken', use_gpu=True)

In [4]:
# ML 모델 성능 비교
best = compare_models()

In [5]:
print(best)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=2200, verbose=0,
                     warm_start=False)

In [6]:
# analyze model
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

In [7]:
# test 데이터 불러오기
# test = pd.read_csv('data/test.csv')
test = pd.read_csv('test_preprocessed.csv')

In [8]:
prediction = predict_model(best)

In [9]:
check_metric(prediction['ProdTaken'], prediction['Label'], metric = 'Accuracy')

0.8807

In [10]:
# 테스트셋 predict
prediction = predict_model(best, data=test)

In [11]:
prediction.head()

,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,Label,Score
0,0.325581,0,3,0.000000,3,2,2,5.000000,1,3.0,1,1.0,0,2,0,1.0,2,0.191118,0,0.88
1,0.651163,1,2,0.305556,3,2,3,3.701827,1,4.0,1,1.0,1,5,0,1.0,2,0.194732,0,0.94
2,0.441860,1,3,0.611111,3,2,3,4.000000,1,3.0,1,5.0,0,5,1,0.0,2,0.208174,0,0.98
3,0.581395,1,1,1.000000,3,2,3,6.000000,1,3.0,3,6.0,0,3,1,2.0,2,0.224718,0,0.82
4,0.162791,1,3,0.194444,1,1,4,4.000000,0,4.0,3,3.0,1,4,1,3.0,1,0.213764,1,0.78

In [40]:
prediction.to_csv('prediction.csv',index = False)

In [12]:
sample_submission = pd.read_csv('data/sample_submission.csv')
sample_submission['ProdTaken'] = prediction['Label']
sample_submission.to_csv('submission2.csv',index = False)